-- Log in as ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

-- Create a warehouse for dbt and data loading
CREATE WAREHOUSE IF NOT EXISTS CRYPTO_WH WITH WAREHOUSE_SIZE = 'XSMALL';

-- Create a database and schema
CREATE DATABASE IF NOT EXISTS CRYPTO_DB;
CREATE SCHEMA IF NOT EXISTS CRYPTO_DB.RAW; -- For raw ingested data
CREATE SCHEMA IF NOT EXISTS CRYPTO_DB.ANALYTICS; -- For dbt transformed data
CREATE SCHEMA IF NOT EXISTS CRYPTO_DB.RAW.MY_SECOND_DBT_MODEL CRYPTO_DB.INFORMATION_SCHEMAL CRYPTO_DB.ANALYTICS; -- For dbt transformed data


-- Create a dedicated role for your project
-- CREATE ROLE IF NOT EXISTS CRYPTO_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON DATABASE CRYPTO_DB TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE CRYPTO_DB TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE CRYPTO_DB TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CRYPTO_DB.RAW TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA CRYPTO_DB.RAW TO ROLE TRANSFORM;
-- GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA CRYPTO_DB.RAW TO ROLE CRYPTO_ROLE;
-- GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA CRYPTO_DB.RAW TO ROLE CRYPTO_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CRYPTO_DB.ANALYTICS TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA CRYPTO_DB.ANALYTICS TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA CRYPTO_DB.ANALYTICS TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA CRYPTO_DB.ANALYTICS TO ROLE TRANSFORM;
-- Create a user and grant the role
-- CREATE USER IF NOT EXISTS CRYPTO_USER PASSWORD = 'YourStrongPassword!' DEFAULT_ROLE = CRYPTO_ROLE DEFAULT_WAREHOUSE = CRYPTO_WH;
-- GRANT ROLE CRYPTO_ROLE TO USER CRYPTO_USER;
-- Test connection with CRYPTO_USER
USE ROLE TRANSFORM;
-- USE WAREHOUSE CRYPTO_WH;
USE DATABASE CRYPTO_DB;
USE SCHEMA CRYPTO_DB.RAW;